"""your message

Revision ID: bc5daa796321
Revises: f3c91ed76c12
Create Date: 2024-12-06 02:43:13.165854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5daa796321'
down_revision = 'f3c91ed76c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
